### ISSUE TITLE
locale parameter not working?

### ISSUE THREAD

**Issue by williambelle** [epflgraph/graphsearch_widgets#1]
Hello, I'm trying to implement the graph-widget-course-courses widget in Edu but the `locale` setting doesn't seem to work. The text "Courses related to this course" is not translated but maybe I'm doing something wrong?

```html
<!DOCTYPE html>
<html lang="fr">
<head>
</head>
<body>
    <graph-widget-course-courses course-id="HUM-120(a)" locale="fr">
    </graph-widget-course-courses>
    <script src="https://cdn.jsdelivr.net/gh/epflgraph/graphsearch_widgets/dist/index.js"></script>
</body>
</html>
```

![Screenshot from](https://github.com/epflgraph/graphsearch_widgets/assets/2843501/de0f88c4-7095-4936-bf6f-483daf75d584)

**Comment by williambelle** [comment]
Hello @tvanbeek, did you have time to take a look?

**Comment by tvanbeek** [comment]
> Hello @tvanbeek, did you have time to take a look?

Thanks for reminding me, I seem to have missed your issue but will pick it up!

**Comment by tvanbeek** [comment]
> > Hello @tvanbeek, did you have time to take a look?
> 
> Thanks for reminding me, I seem to have missed your issue but will pick it up!

There are a few updates:

1.  French translations are added
2. All web components now take the same `id` attribute instead of for example `person-id` or `unit-id`
3. Most text styling is removed,  so for instance `font-family`, `color` and `line-height` are now inherited
