### ISSUE TITLE
Unable to style course description with v1.0.0

### ISSUE THREAD

**Issue by williambelle** [epflgraph/graphsearch_widgets#5]
Hello @tvanbeek, I can't apply my styles for the course description.

Looks like the name has changed. (`course__summary` -> `course__description`).

`course__description` is missing in:
https://github.com/epflgraph/graphsearch_widgets/blob/f288e5d5ab0d9c6a718e31e477071a12c089862b/src/components/course-courses.ts#L47-L48

**Comment by tvanbeek** [comment]
Thanks @williambelle!

This should now be fixed in https://github.com/epflgraph/graphsearch_widgets/tree/v1.0.1
